import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useState } from 'react'

// const inter = Inter({ subsets: ['latin']})

export default function Home() {

  const [data, setData] = useState({});
  const [location, setLocation] = useState('');
  const [weather, setWeather] = useState();
  const [errorMessage, setErrorMessage] = useState('');

  const [temp, setTemp] = useState('');
  const [feelsLike, setFeelsLike] = useState('');
  const [gust, setGust] = useState('');

  var apiKey = "ff8da5a2590a2801d29b651427a31d17";
  var lang = "en";
  var units = "metric";
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lang=${lang}`;

  const searchLocation = (event) => {
    if(event.key === "Enter"){
      axios.get(url)
      .then((response) => {
        console.clear();
        setData(response.data)
        console.log(response.data)
        setWeather(response.data.weather)
        setErrorMessage("")
        setTemp(response.data.main.temp)
        setFeelsLike(response.data.main.feels_like)
        setGust(response.data.wind.gust)
        console.log(feelsLike)
      }).catch(err => {
        console.log(err)
        setErrorMessage("Please enter another location")
        setData({})
        setWeather()
        setTemp()
        setFeelsLike()
        setGust()
      })
      setLocation('');
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input className={styles.input}
          value={location}
          onChange={event => setLocation(event.target.value)}
          placeholder="Enter location"
          onKeyDown={searchLocation}
          type="text"
        />
        <div className={styles.title}>
        {errorMessage}
        {data.name}
        </div>
        {
          weather && weather.map((w, index) => {
            return(
              <div className={styles.text} key={index}>
                <div>{w.description}</div>
                <div>{w.main}</div>
                <div>{temp} °C</div>
                <div>{feelsLike} °C</div>
                <div>{gust} m/s</div>
              </div>
            )
          })
        }
      </main>

      <footer className={styles.footer}>
           © 2023 Alex Somerville 🗯️
      </footer>
    </div>
  )
}
